services:
  inventorylabel:
    image: registry.dsra.io/dmc/inventory-label
    volumes:
      - ./QrSheets:/app/QrSheets
      - ./database:/app/database

    build:
      context: .
      dockerfile: ./Dockerfile
